2017-11-12 14:52:04,043 [Thread-18:11992] [django.request:152] [WARNING]- Not Found: /pic
2017-11-12 14:52:04,442 [Thread-20:2028] [django.request:152] [WARNING]- Not Found: /favicon.ico
2017-11-12 14:52:40,485 [Thread-25:5304] [django.request:152] [WARNING]- Not Found: /pic
2017-11-12 14:53:16,061 [Thread-122:6904] [django.request:152] [WARNING]- Not Found: /jape
2017-11-12 14:53:19,300 [Thread-124:8224] [django.request:152] [WARNING]- Not Found: /pic
2017-11-12 14:53:23,973 [Thread-127:8000] [django.request:152] [WARNING]- Not Found: /manager/login
2017-11-12 14:53:40,989 [Thread-131:3952] [django.request:152] [WARNING]- Not Found: /index-new
2017-11-20 13:21:08,653 [Thread-9:23976] [django.request:152] [WARNING]- Not Found: /static/admin/css/base.css
2017-11-20 13:21:08,654 [Thread-10:27604] [django.request:152] [WARNING]- Not Found: /static/admin/css/login.css
2017-11-20 13:21:09,194 [Thread-11:20320] [django.request:152] [WARNING]- Not Found: /favicon.ico
2017-11-20 13:23:40,521 [Thread-13:16620] [django.request:152] [WARNING]- Not Found: /static/admin/css/base.css
2017-11-20 13:23:40,542 [Thread-14:27072] [django.request:152] [WARNING]- Not Found: /static/admin/css/login.css
2017-11-20 13:23:56,005 [Thread-3:23404] [django.request:152] [WARNING]- Not Found: /static/admin/css/base.css
2017-11-20 13:23:56,007 [Thread-4:25800] [django.request:152] [WARNING]- Not Found: /static/admin/css/login.css
2017-11-20 14:57:25,758 [Thread-13:12752] [django.request:152] [WARNING]- Not Found: /uploads/avatar/2017/10/20/u3323249715914891285fm23gp0.jpg
2017-11-20 14:57:25,772 [Thread-16:26180] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/02/17_38_01_xudong.jpg
2017-11-20 14:57:25,778 [Thread-17:27192] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/18_27_14_xudong.jpg
2017-11-20 14:57:25,782 [Thread-18:26512] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/11_34_56_xudong.jpg
2017-11-20 14:57:25,785 [Thread-19:23176] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/11_36_46_xudong.jpg
2017-11-20 14:57:25,787 [Thread-20:16924] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/11_38_20_xudong.jpg
2017-11-20 14:57:25,792 [Thread-21:27472] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/18_21_06_xudong.jpg
2017-11-20 16:37:05,923 [Thread-12:15976] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/18_27_14_xudong.jpg
2017-11-20 16:37:05,924 [Thread-10:22112] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/02/17_38_01_xudong.jpg
2017-11-20 16:37:05,925 [Thread-9:5632] [django.request:152] [WARNING]- Not Found: /uploads/avatar/2017/10/20/u3323249715914891285fm23gp0.jpg
2017-11-20 16:37:05,968 [Thread-16:25784] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/18_21_06_xudong.jpg
2017-11-20 16:37:05,973 [Thread-17:23920] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/11_38_20_xudong.jpg
2017-11-20 16:37:06,011 [Thread-22:15560] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/11_34_56_xudong.jpg
2017-11-20 16:37:06,015 [Thread-23:27016] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/11_36_46_xudong.jpg
2017-11-20 16:38:25,694 [Thread-13:15496] [django.request:152] [WARNING]- Not Found: /uploads/avatar/2017/10/20/u3323249715914891285fm23gp0.jpg
2017-11-20 16:38:25,699 [Thread-16:26752] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/02/17_38_01_xudong.jpg
2017-11-20 16:38:25,702 [Thread-17:4168] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/18_27_14_xudong.jpg
2017-11-20 16:38:25,705 [Thread-18:11820] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/11_34_56_xudong.jpg
2017-11-20 16:38:25,712 [Thread-19:19672] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/11_36_46_xudong.jpg
2017-11-20 16:38:25,719 [Thread-20:15272] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/11_38_20_xudong.jpg
2017-11-20 16:38:25,727 [Thread-21:19428] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/18_21_06_xudong.jpg
2017-11-24 14:28:14,382 [Thread-9:15412] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/11_36_46_xudong.jpg
2017-11-24 14:28:14,384 [Thread-11:2580] [django.request:152] [WARNING]- Not Found: /uploads/avatar/2017/10/20/u3323249715914891285fm23gp0.jpg
2017-11-24 14:28:14,384 [Thread-10:9648] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/11_34_56_xudong.jpg
2017-11-24 14:28:14,396 [Thread-12:8656] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/18_21_06_xudong.jpg
2017-11-24 14:28:14,413 [Thread-13:1328] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/11_38_20_xudong.jpg
2017-11-24 14:28:14,418 [Thread-15:9528] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/01/18_27_14_xudong.jpg
2017-11-24 14:28:14,422 [Thread-17:5204] [django.request:152] [WARNING]- Not Found: /uploads/images/2017/11/02/17_38_01_xudong.jpg
2017-11-24 14:34:54,073 [Thread-10:12784] [django.request:152] [WARNING]- Not Found: /favicon.ico
2017-11-29 15:18:33,115 [Thread-43:8744] [django.request:152] [WARNING]- Not Found: /favicon.ico
2017-11-29 15:47:01,663 [Thread-1:2088] [django.request:135] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python36-32\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python36-32\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Python36-32\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Python36-32\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Python36-32\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python36-32\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "C:\Python36-32\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "C:\Python36-32\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "C:\Python36-32\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python36-32\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'focus_note.recmd' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python36-32\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\code\PycharmProjects\cms\focus\views.py", line 552, in index
    return render(request, 'focus/index.html', context)
  File "C:\Python36-32\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Python36-32\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Python36-32\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Python36-32\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python36-32\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Python36-32\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Python36-32\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Python36-32\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Python36-32\lib\site-packages\django\template\defaulttags.py", line 173, in render
    len_values = len(values)
  File "C:\Python36-32\lib\site-packages\django\db\models\query.py", line 232, in __len__
    self._fetch_all()
  File "C:\Python36-32\lib\site-packages\django\db\models\query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Python36-32\lib\site-packages\django\db\models\query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "C:\Python36-32\lib\site-packages\django\db\models\sql\compiler.py", line 894, in execute_sql
    raise original_exception
  File "C:\Python36-32\lib\site-packages\django\db\models\sql\compiler.py", line 884, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python36-32\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python36-32\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python36-32\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Python36-32\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python36-32\lib\site-packages\django\db\backends\mysql\base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "C:\Python36-32\lib\site-packages\pymysql\cursors.py", line 166, in execute
    result = self._query(query)
  File "C:\Python36-32\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Python36-32\lib\site-packages\pymysql\connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python36-32\lib\site-packages\pymysql\connections.py", line 1057, in _read_query_result
    result.read()
  File "C:\Python36-32\lib\site-packages\pymysql\connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "C:\Python36-32\lib\site-packages\pymysql\connections.py", line 1014, in _read_packet
    packet.check_error()
  File "C:\Python36-32\lib\site-packages\pymysql\connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python36-32\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'focus_note.recmd' in 'field list'")
